version: "3.7"

services:
  php:
    build: ./docker/php
    tty: true
    volumes:
      - ./app:/var/www

  nginx:
    build: ./docker/nginx
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./logs:/var/logs/nginx