version: "3.7"

services:
  php-fpm:
    build: ./docker/php
    volumes:
      - ./app:/var/www
      - .env:/var/www/.env
    command: sh -c 'composer install && php-fpm'


  nginx:
    image: nginx:1.18
    working_dir: /var/www
    ports:
      - 8080:80
    depends_on:
        - php-fpm
    environment:
        - FASTCGI_URL=php-fpm:9000
    volumes:
        - ./app:/var/www
        - ./docker/nginx:/etc/nginx/templates
        - ./logs:/var/logs/nginx